config/routes.rb
Rails.application.routes.draw do
  
  root 'static#landing'

  devise_for :users

  resources :feeds do
    member do
      get 'fetch'
      put 'subscribe'
      put 'unsubscribe/:postbox_id', to: 'feeds#unsubscribe', as: :unsubscribe
    end

    collection do
      get 'fetch', to: 'feeds#fetch_all'
    end
  end
  resources :feed_entries
  
  resources :postboxes

end

app/models/feed_entry.rb
class FeedEntry < ActiveRecord::Base
  belongs_to :feed
  has_and_belongs_to_many :leaflets, :join_table => "enties_in_leaflets"

  # Distribute new records after creation
  after_create :distribute_to_feed_postboxes

  # Orders itself from newest to oldest by default
  default_scope { order('published_at DESC') }

  ##
  # Enhance entry content through additional readability parsing
  #
  def enhance
    require 'open-uri'

    source = open(self.url).read
    return Readability::Document.new(source).content
  end

  ##
  # Distribute entry for all users subscribed to entries' feed
  #
  def distribute_to_feed_postboxes
    self.feed.postboxes.each do |postbox|
      self.distribute_to(postbox)
    end
  end

  ##
  # Distribute entry to the pending leaflet for specified user
  #
  def distribute_to(postbox)
    leaflet = postbox.find_or_create_active_leaflet
    leaflet.entries << self unless leaflet.entries.exists? self
  end

end

app/controllers/feed_entries_controller.rb
class FeedEntriesController < ApplicationController
  before_action :set_feed_entry, only: [:show, :edit, :update, :destroy]

  # GET /feed_entries
  # GET /feed_entries.json
  def index
    @feed_entries = FeedEntry.all
  end

  # GET /feed_entries/1
  # GET /feed_entries/1.json
  def show
  end

  # GET /feed_entries/new
  def new
    @feed_entry = FeedEntry.new
  end

  # GET /feed_entries/1/edit
  def edit
  end

  # POST /feed_entries
  # POST /feed_entries.json
  def create
    @feed_entry = FeedEntry.new(feed_entry_params)

    respond_to do |format|
      if @feed_entry.save
        format.html { redirect_to @feed_entry, notice: 'Feed entry was successfully created.' }
        format.json { render :show, status: :created, location: @feed_entry }
      else
        format.html { render :new }
        format.json { render json: @feed_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feed_entries/1
  # PATCH/PUT /feed_entries/1.json
  def update
    respond_to do |format|
      if @feed_entry.update(feed_entry_params)
        format.html { redirect_to @feed_entry, notice: 'Feed entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed_entry }
      else
        format.html { render :edit }
        format.json { render json: @feed_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feed_entries/1
  # DELETE /feed_entries/1.json
  def destroy
    @feed_entry.destroy
    respond_to do |format|
      format.html { redirect_to feed_entries_url, notice: 'Feed entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed_entry
      @feed_entry = FeedEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_entry_params
      params.require(:feed_entry).permit(:feed_id, :title, :url, :published_at, :image_url, :summary, :original_id)
    end
end

app/helpers/feed_entries_helper.rb
module FeedEntriesHelper
end

app/views/feed_entries/_feed_entry.html.erb
<tr><td>

<div class="object-id">
  #<%= feed_entry.id %>
</div>

<p>
  <strong>Original ID:</strong>
  <%= feed_entry.original_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= link_to feed_entry.title, feed_entry %>
</p>

<p>
  <strong>Url:</strong>
  <%= link_to feed_entry.url, feed_entry.url %>
</p>

<p>
  <strong>Yandex Rich Content</strong>
  <%= link_to 'check', "http://rca.yandex.com/?key=24LbkxMc&url=#{feed_entry.url}" %>
</p>

<p>
  <strong>Published at:</strong>
  <%= feed_entry.published_at %>
</p>

<p>
  <strong>Image url:</strong>
  <%= feed_entry.image_url %>
</p>

<p>
  <strong>Summary:</strong>
  <%= feed_entry.summary %>
</p>


</td></tr>

app/views/feed_entries/_form.html.erb
<%= form_for(@feed_entry) do |f| %>
  <% if @feed_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed_entry.errors.count, "error") %> prohibited this feed_entry from being saved:</h2>

      <ul>
      <% @feed_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :feed_id %><br>
    <%= f.text_field :feed_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.datetime_select :published_at %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :original_id %><br>
    <%= f.text_field :original_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feed_entries/edit.html.erb
<h1>Editing feed_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed_entry %> |
<%= link_to 'Back', feed_entries_path %>

app/views/feed_entries/index.html.erb
<h1>Listing feed_entries</h1>

<table>
  <thead>
    <tr>
      <th>Feed</th>
      <th>Title</th>
      <th>Url</th>
      <th>Published at</th>
      <th>Image url</th>
      <th>Summary</th>
      <th>Original</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feed_entries.each do |feed_entry| %>
      <tr>
        <td><%= feed_entry.feed %></td>
        <td><%= feed_entry.title %></td>
        <td><%= feed_entry.url %></td>
        <td><%= feed_entry.published_at %></td>
        <td><%= feed_entry.image_url %></td>
        <td><%= feed_entry.summary %></td>
        <td><%= feed_entry.original_id %></td>
        <td><%= link_to 'Show', feed_entry %></td>
        <td><%= link_to 'Edit', edit_feed_entry_path(feed_entry) %></td>
        <td><%= link_to 'Destroy', feed_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed entry', new_feed_entry_path %>

app/views/feed_entries/new.html.erb
<h1>New feed_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', feed_entries_path %>

app/views/feed_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Feed:</strong>
  <%= @feed_entry.feed %>
</p>

<p>
  <strong>Original ID:</strong>
  <%= @feed_entry.original_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @feed_entry.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= link_to @feed_entry.url, @feed_entry.url %>
</p>

<p>
  <strong>Yandex Rich Content</strong>
  <%= link_to 'check', "http://rca.yandex.com/?key=24LbkxMc&url=#{@feed_entry.url}" %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @feed_entry.published_at %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @feed_entry.image_url %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @feed_entry.summary %>
</p>

<p>
  <strong>Enhanced content:</strong>
  <%= raw @feed_entry.enhance %>
</p>

<%= link_to 'Back', feed_path(@feed_entry.feed) %>