config/routes.rb
Rails.application.routes.draw do
  
  root 'static#landing'

  devise_for :users

  resources :feeds do
    member do
      get 'fetch'
      put 'subscribe'
      put 'unsubscribe/:postbox_id', to: 'feeds#unsubscribe', as: :unsubscribe
    end

    collection do
      get 'fetch', to: 'feeds#fetch_all'
    end
  end
  resources :feed_entries
  
  resources :postboxes

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  # Contains many entries
  has_many :entries, class_name: 'FeedEntry', dependent: :destroy

  # Can be subscribed to by users 
  has_many :subscriptions
  has_many :postboxes, through: :subscriptions

  # Fetch latest entries after feed creation
  after_create :fetch

  # Validations
  validates_uniqueness_of :url

  ##
  # Get new entries from feed URL, create entries
  #
  # [todo] - integrate Feedjira update method to parse faster
  def fetch
    feed = Feedjira::Feed.fetch_and_parse(self.url)
    
    # Handle empty feed fetching
    unless feed.is_a?(Fixnum)
      self.update!(title: feed.title) if self.title.nil?

      feed.entries.each do |entry|
        unless self.entries.exists? :original_id => entry.id
          self.entries.create!(
            :title         => entry.title,
            :summary      => entry.summary,
            :url          => entry.url,
            :published_at => entry.published,
            :original_id  => entry.id
          )
        end
      end
    else
      logger.error "[ERROR] Feed expected, got Fixnum instead (in Feed#fetch for feed.id #{self.id})"
      return false
    end

  end

  ##
  # Update all existing feeds
  #
  # [todo] - send owning user as a param
  #
  def self.fetch_all
    Feed.all.each do |feed|
      feed.fetch
    end
  end

  ##
  # Return feed subscribers
  #
  def subscribers 
    return self.postboxes
  end 

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy, :fetch, :subscribe, :unsubscribe]
  before_action :set_postbox, only: [:subscribe, :unsubscribe]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  ##
  # Update feed with new entries
  #
  def fetch

  end

  ##
  # Update all personal feeds
  #
  def fetch_all
    
  end

  ##
  # Subscribe to the feed with one of the postboxes
  #
  # == Routes:
  #  PUT /feeds/:id/subscribe
  #
  def subscribe
    respond_to do |format|
      if @postbox.feeds.include?(@feed)
        format.html { redirect_to feeds_url, notice: "Selected postbox is already subscribed to the feed." }
      else
        @postbox.feeds << @feed
        format.html { redirect_to feeds_url, notice: "Successfully subscribed to feed with #{@postbox.email}." }
      end
    end
  end

  ##
  # Unsubscribe selected postbox from the feed 
  #
  # == Routes:
  #  PUT /feeds/:id/unsubscribe
  #
  def unsubscribe
    respond_to do |format|
      if @postbox.feeds.delete(@feed)
        format.html { redirect_to @postbox, notice: "Successfully unsubscribed from the feed." }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:url)
    end

    def set_postbox
      @postbox = Postbox.find(params[:postbox_id])
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/_subscription_form.html.erb
<%= form_tag subscribe_feed_path(feed), method: :put do %>
  <div class="field" style="margin-top: 12px;">
    <%= select_tag :postbox_id, options_from_collection_for_select(current_user.postboxes, "id", "email") %>
    <%= submit_tag 'Subscribe' %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Listing feeds</h1>

<p id="notice"><%= notice %></p>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Count</th>
      <th>Subscribed?</th>
      <th colspan="3"></th>
      <th>Subscribe with</th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td>
          <%= feed.title %> <br />
          <span class="gray"><%= feed.url %></span>
        </td>
        <td><%= feed.entries.count %></td>
        <td>
          <% if user_signed_in? %>
            <%= current_user.feeds.exists?(feed) ? '&#10003;'.html_safe : '&nbsp;'.html_safe %>
          <% end %>
        </td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
        <td>
          <%= render 'subscription_form', :feed => feed if user_signed_in? %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @feed.title %>
</p>

<p>
  <strong>Count:</strong>
  <%= @feed.entries.count %>
</p>

<table> 
  <caption>Feed entries</caption>
  <tbody>
    <%= render @feed.entries %>
  </tbody>
</table>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>