config/routes.rb
Rails.application.routes.draw do
  
  root 'static#landing'

  devise_for :users

  resources :feeds do
    member do
      get 'fetch'
      put 'subscribe'
      put 'unsubscribe/:postbox_id', to: 'feeds#unsubscribe', as: :unsubscribe
    end

    collection do
      get 'fetch', to: 'feeds#fetch_all'
    end
  end
  resources :feed_entries
  
  resources :postboxes

end

app/models/postbox.rb
class Postbox < ActiveRecord::Base

  # Relates to owning user
  belongs_to :user
  validates :user, presence: true

  # Contains many leaflets issued
  has_many :leaflets

  # Each postbox is subscribed to different feeds 
  has_many :subscriptions
  has_many :feeds, through: :subscriptions

  # Has different issue periodity
  enum periodity: [:daily, :three_times_a_day, :weekly]

  ##
  # Return owner of the postbox
  #
  def owner
    return self.user
  end

  ##
  # Find or create leaflet ready for population
  #
  # [todo] - test we have single leaflet active at any time
  def find_or_create_active_leaflet
    leaflet = self.leaflets.populating.first
    
    if leaflet.nil?
      return self.leaflets.create
    else
      return leaflet
    end
  end

end

app/controllers/postboxes_controller.rb
class PostboxesController < ApplicationController
  before_action :set_postbox, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /postboxes
  # GET /postboxes.json
  def index
    @postboxes = Postbox.all
  end

  # GET /postboxes/1
  # GET /postboxes/1.json
  def show
  end

  # GET /postboxes/new
  def new
    @postbox = Postbox.new
  end

  # GET /postboxes/1/edit
  def edit
  end

  # POST /postboxes
  # POST /postboxes.json
  def create
    @postbox = current_user.postboxes.new(postbox_params)

    respond_to do |format|
      if @postbox.save
        format.html { redirect_to @postbox, notice: 'Postbox was successfully created.' }
        format.json { render :show, status: :created, location: @postbox }
      else
        format.html { render :new }
        format.json { render json: @postbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postboxes/1
  # PATCH/PUT /postboxes/1.json
  def update
    respond_to do |format|
      if @postbox.update(postbox_params)
        format.html { redirect_to @postbox, notice: 'Postbox was successfully updated.' }
        format.json { render :show, status: :ok, location: @postbox }
      else
        format.html { render :edit }
        format.json { render json: @postbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postboxes/1
  # DELETE /postboxes/1.json
  def destroy
    @postbox.destroy
    respond_to do |format|
      format.html { redirect_to postboxes_url, notice: 'Postbox was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postbox
      @postbox = Postbox.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def postbox_params
      params.require(:postbox).permit(:email, :periodity)
    end
end

app/helpers/postboxes_helper.rb
module PostboxesHelper
end

app/views/postboxes/_form.html.erb
<%= form_for(@postbox) do |f| %>
  <% if @postbox.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@postbox.errors.count, "error") %> prohibited this postbox from being saved:</h2>

      <ul>
      <% @postbox.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :periodity %><br>
    <%= f.select :periodity, 
                options_for_select(
                    Postbox.periodities.collect { |s| [s[0].humanize, s[0]] }, 
                    selected: @postbox.periodity), 
                {}, 
                class: "form-control" %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/postboxes/edit.html.erb
<h1>Editing postbox</h1>

<%= render 'form' %>

<%= link_to 'Show', @postbox %> |
<%= link_to 'Back', postboxes_path %>

app/views/postboxes/index.html.erb
<h1>Listing postboxes</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Periodity</th>
      <th>Owner</th>
      <th>Records in active leaflet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @postboxes.each do |postbox| %>
      <tr>
        <td><%= postbox.email %></td>
        <td><%= postbox.periodity %></td>
        <td><%= postbox.user.email %></td>
        <td><%= postbox.find_or_create_active_leaflet.entries.count %></td>
        <td><%= link_to 'Show', postbox %></td>
        <td><%= link_to 'Edit', edit_postbox_path(postbox) %></td>
        <td><%= link_to 'Destroy', postbox, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Postbox', new_postbox_path %>

app/views/postboxes/new.html.erb
<h1>New postbox</h1>

<%= render 'form' %>

<%= link_to 'Back', postboxes_path %>

app/views/postboxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @postbox.email %>
</p>

<p>
  <strong>Periodity:</strong>
  <%= @postbox.periodity %>
</p>

<p>
  <strong>Feeds in subscription:</strong>
  <ul>
    <% @postbox.feeds.each do |feed| %>
      <li>
        <%= link_to feed.title, feed %>
        (<%= link_to 'unsubscribe', unsubscribe_feed_path(feed, @postbox), method: :put %>)
      </li>
    <% end %>
  </ul>
</p>

<table> 
  <caption>Leaflets</caption>
  <tbody>
    <%= render @postbox.leaflets %>
  </tbody>
</table>


<%= link_to 'Edit', edit_postbox_path(@postbox) %> |
<%= link_to 'Back', postboxes_path %>